# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsuser',
            name='usersex',
            field=models.CharField(choices=[(0, '男'), (1, '女')], default=0, max_length=10, verbose_name='性别'),
        ),
    ]
