# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0002_auto_20180711_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='ip地址')),
            ],
            options={
                'verbose_name': 'ip地址',
                'verbose_name_plural': 'ip地址',
                'db_table': 'ip_addr',
            },
        ),
    ]
