# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0003_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(max_length=32, verbose_name='书名')),
                ('art_info', models.CharField(max_length=255, verbose_name='简单描述')),
                ('art_img', models.ImageField(max_length=150, upload_to='media/arts_ups/%Y/%m', verbose_name='封面')),
                ('art_create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='更新时间')),
                ('art_price', models.IntegerField(default=0, verbose_name='单价')),
                ('art_flag', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='小说控制字段')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
                'db_table': 'art',
                'ordering': ['-art_create_time'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=32, verbose_name='类别')),
                ('tag_info', models.CharField(max_length=64, verbose_name='类别描述')),
                ('tag_create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('tag_flag', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='控制字段')),
            ],
            options={
                'verbose_name': '小说类别',
                'verbose_name_plural': '小说类别',
                'db_table': 'tag',
                'ordering': ['-tag_create_time'],
            },
        ),
        migrations.AddField(
            model_name='art',
            name='art_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts_app.Tag', verbose_name='关联类别标签'),
        ),
    ]
