# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0004_auto_20180727_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='章节标题')),
                ('content', models.TextField(verbose_name='小说章节内容')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='添加时间')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts_app.Art', verbose_name='小说')),
            ],
            options={
                'verbose_name': '小说章节',
                'verbose_name_plural': '小说章节',
                'db_table': 'art_chapter',
            },
        ),
    ]
