# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0006_artsuser_uphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artsuser',
            name='uphone',
        ),
    ]
